name: undone
version: 0.4.1-dev
description: A library for undo and redo.
author: Ross Smith <dev@futureperfect.info>
homepage: https://github.com/rmsmith/undone
documentation: http://futureperfect.info/undone/index.html#undone
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  bench: '>=0.2.26'
  browser: '>=0.10.0'   
  unittest: '>=0.10.1'
