name: undone
version: 0.5.1-dev
description: A library for undo and redo.
author: Ross Smith <dev@futureperfect.info>
homepage: https://github.com/rmsmith/undone
documentation: http://rmsmith.github.com/undone/index.html#undone
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
dev_dependencies:
  bench: '>=0.4.0'
  browser: '>=0.10.0'
  unittest: '>=0.11.0'
