name: undone
version: 0.6.2-dev
description: A library for undo and redo.
author: Ross Smith <dev@futureperfect.info>
homepage: https://github.com/rmsmith/undone
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  bench: '>=0.4.0'
  browser: '>=0.10.0'
  unittest: '>=0.11.0'
